# This file was generated by update.sh from the fetchCommit uses in default.nix.
# Do not edit this file by hand. Instead, edit default.nix and run update.sh
{
  "f645a37598ad1095e26ff6cb9b89e1a611cb23bf" = {
    hash = "06zcpbh8fzi04bi7sirx2gjg7hq0jg6d47j2z31h889969svwflc";
    path = "/nix/store/4ppkx6kccgm87z7zki58ry0nwdqfy7a3-source";
  };
}
